### ISSUE TITLE
cocoadocs reparse link does not work

### ISSUE THREAD

**Issue by mylyuic** [CocoaPods/cocoadocs.org#521]
Trying to force a reparse of my pod by visiting http://api.cocoadocs.org:4567/redeploy/[Podname]/[Version]. But got a connection error like below:

![image](https://cloud.githubusercontent.com/assets/883082/26186421/9c71e1a0-3b46-11e7-868b-09aded3f62cc.png)

**Comment by orta** [comment]
Should be working now - thanks!

**Comment by Decybel07** [comment]
Sorry but this bug still exists
![zrzut ekranu 2017-05-19 o 12 07 59](https://cloud.githubusercontent.com/assets/15947101/26243364/ea24a5e0-3c8b-11e7-8002-4ebf9879bcb6.png)

**Comment by orta** [comment]
This is an issue on your side:

![screen shot 2017-05-19 at 11 11 08](https://cloud.githubusercontent.com/assets/49038/26243476/e3243e34-3c83-11e7-9342-94ac773ce672.png)

**Comment by Decybel07** [comment]
Thank you
